title: "Alessio Coser"
email: unexistent@ema.il
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Alessio Coser
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
authors:
  alessio:
    name: Alessio Coser
    display_name: Alessio Coser
    avatar: 'assets/images/alessio.png'
    email: unexistent@ema.il
    web: https://www.alessiocoser.com/
    twitter: https://twitter.com/AlessioCoser
    linkedin: https://linkedin.com/in/AlessioCoser
    description: "I am a passionate advocate of eXtreme Programming. As a software crafter, I aim to continuously learn better ways to deliver working software faster."
exclude:
  - "LICENSE.txt"
  - "CNAME"
  - "vendor"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
