title: "Alessio Coser"
# logo: "/docs/images/logo_with_text.svg"
remote_theme: alshedivat/al-folio
# aux_links:
#   "Daikon on GitHub":
#     - "//github.com/DaikonWeb/daikon"
footer_content: "An eXtreme Programmer"