title: "Affiliates"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Alessio Coser
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics:

# Authors
authors:
  alessio:
    name: Alessio Coser
    display_name: Alessio Coser
    avatar: 'assets/images/alessio.png'
    email: unexistent@ema.il
    web: https://www.alessiocoser.com/
    twitter: https://twitter.com/AlessioCoser
    description: "An eXtreme Programmer. I strive at continuously improving my knowledge, by studying practices, languages, methodologies and applying what I learn to my everyday work. I strongly believe in teamwork and in the fact that the team should be autonomous and responsible during the whole life-cycle of a product or a service, from its development to its release and to software maintenance."

# Social
social:
  linkedin: https://linkedin.com/in/AlessioCoser
  twitter: https://twitter.com/AlessioCoser

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
